// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wkuqinknlhpvwedyvend.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndrdXFpbmtubGhwdndlZHl2ZW5kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4OTk3MTIsImV4cCI6MjA3MTQ3NTcxMn0.ZNlqEhFFOz5nLUIDR1TV6HHMtZwFk4QcL5_3-u_dDj8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});